language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

script:
  - npm i
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./dist/
  on:
    branch: master
